dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  http: ^1.2.1
  process_run: ^0.14.2
  file_picker: ^8.0.3
  pdf: ^3.10.8
  printing: ^5.12.0
  intl: ^0.19.0
  uuid: ^4.4.0
  equatable: ^2.0.5
  logger: ^2.3.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  mobx_codegen: ^2.6.1
  json_serializable: ^6.8.0