dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  provider: ^6.1.2
  json_serializable: ^6.8.0
  path_provider: ^2.1.3
  process_run: ^0.14.2

dev_dependencies:
  build_runner: ^2.4.10
  mobx_codegen: ^2.6.1
  json_annotation: ^4.9.0