name: software_requirements_analyzer
description: 'Sistema desktop Flutter para análise e gerenciamento de requisitos de software.'
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '^3.6.1'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  # Estado e gerenciamento
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # Armazenamento local e persistência
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  hive: ^2.2.3

  # Requisições HTTP e integrações externas
  http: ^1.2.1

  # Execução de comandos locais
  process_run: ^0.14.2

  # Manipulação de arquivos
  file_picker: ^8.0.3

  # Geração de relatórios PDF e HTML
  pdf: ^3.10.8
  printing: ^5.12.0

  # Internacionalização e formatação
  intl: ^0.19.0

  # Utilitários diversos
  uuid: ^4.4.0
  equatable: ^2.0.5
  logger: ^2.3.0

  # Serialização JSON
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  mobx_codegen: ^2.6.1
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/config.json
    - assets/images/

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: asset: assets/fonts/Roboto-Bold.ttf
        weight: 700