name: software_analyzer
description: 'Software Analyzer - Flutter Desktop'
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '^3.6.1'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  provider: ^6.1.2
  json_serializable: ^6.8.0
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.10
  mobx_codegen: ^2.6.1
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/config.json